version: "3.8"

networks:
  galera:
    external: true

services:
  ddoser:
    image: dns_ddoser:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dns_ddos.yaml.recover:/dns_ddos.yaml
    deploy:
      replicas: 50
    networks:
      - galera
    entrypoint: "/dns_ddoser --count 10000 --dns 8.8.8.8:53 --quiet"
