version: "3.8"

services:
  ddoser:
    image: garagator3000/dns_ddoser:1.3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dns_ddos.yaml:/dns_ddos.yaml
    network_mode: host
    deploy:
      replicas: 4
    entrypoint: "/dns_ddoser --count 100 --dns 10.0.0.22:5300 --loglvl info"
