version: "3.8"

services:
  ddoser:
    image: dns_ddoser:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dns_ddos.yaml:/dns_ddos.yaml
    network_mode: host
    deploy:
      replicas: 5
    entrypoint: "/dns_ddoser --count 100 --dns 255.255.255.254:5300 --quiet --timeout 30000"
